# Generated by Django 5.2.2 on 2025-09-30 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisCople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_analisis', models.CharField(help_text='Identificador único del análisis', max_length=50, unique=True, verbose_name='ID de análisis')),
                ('timestamp_captura', models.DateTimeField(help_text='Momento en que se capturó la imagen', verbose_name='Timestamp de captura')),
                ('timestamp_procesamiento', models.DateTimeField(auto_now_add=True, help_text='Momento en que se procesó el análisis', verbose_name='Timestamp de procesamiento')),
                ('tipo_analisis', models.CharField(choices=[('segmentacion_completa', 'Segmentación Completa (Defectos + Piezas)'), ('segmentacion_defectos', 'Solo Segmentación de Defectos'), ('segmentacion_piezas', 'Solo Segmentación de Piezas')], default='segmentacion_completa', max_length=30, verbose_name='Tipo de análisis')),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='procesando', max_length=20, verbose_name='Estado')),
                ('archivo_imagen', models.CharField(help_text='Nombre del archivo de imagen generado', max_length=255, verbose_name='Archivo de imagen')),
                ('archivo_json', models.CharField(help_text='Nombre del archivo JSON con metadatos', max_length=255, verbose_name='Archivo JSON')),
                ('resolucion_ancho', models.IntegerField(verbose_name='Ancho de imagen')),
                ('resolucion_alto', models.IntegerField(verbose_name='Alto de imagen')),
                ('resolucion_canales', models.IntegerField(verbose_name='Canales de imagen')),
                ('tiempo_captura_ms', models.FloatField(verbose_name='Tiempo de captura (ms)')),
                ('tiempo_segmentacion_defectos_ms', models.FloatField(blank=True, null=True, verbose_name='Tiempo de segmentación defectos (ms)')),
                ('tiempo_segmentacion_piezas_ms', models.FloatField(blank=True, null=True, verbose_name='Tiempo de segmentación piezas (ms)')),
                ('tiempo_total_ms', models.FloatField(verbose_name='Tiempo total (ms)')),
                ('metadatos_json', models.JSONField(default=dict, help_text='Metadatos completos del análisis en formato JSON', verbose_name='Metadatos JSON')),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si el análisis falló', verbose_name='Mensaje de error')),
            ],
            options={
                'verbose_name': 'Análisis de Cople',
                'verbose_name_plural': 'Análisis de Coples',
                'ordering': ['-timestamp_procesamiento'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la configuración', max_length=100, unique=True, verbose_name='Nombre de configuración')),
                ('ip_camara', models.GenericIPAddressField(default='172.16.1.21', help_text='Dirección IP de la cámara GigE', verbose_name='IP de la cámara')),
                ('umbral_confianza', models.FloatField(default=0.55, help_text='Umbral mínimo de confianza para detecciones (0.0 - 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Umbral de confianza')),
                ('umbral_iou', models.FloatField(default=0.35, help_text='Umbral IoU para supresión de no máximos (0.0 - 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Umbral IoU')),
                ('configuracion_robustez', models.CharField(choices=[('original', 'Original - Alta precisión'), ('moderada', 'Moderada - Balanceada'), ('permisiva', 'Permisiva - Alta sensibilidad'), ('ultra_permisiva', 'Ultra Permisiva - Condiciones extremas')], default='original', help_text='Configuración de robustez del sistema', max_length=20, verbose_name='Configuración de robustez')),
                ('activa', models.BooleanField(default=False, help_text='Indica si esta es la configuración activa del sistema', verbose_name='Configuración activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticasSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de las estadísticas', unique=True, verbose_name='Fecha')),
                ('total_analisis', models.IntegerField(default=0, help_text='Número total de análisis realizados', verbose_name='Total de análisis')),
                ('analisis_exitosos', models.IntegerField(default=0, help_text='Número de análisis completados exitosamente', verbose_name='Análisis exitosos')),
                ('analisis_con_error', models.IntegerField(default=0, help_text='Número de análisis que fallaron', verbose_name='Análisis con error')),
                ('total_defectos_detectados', models.IntegerField(default=0, help_text='Número total de defectos segmentados', verbose_name='Total defectos detectados')),
                ('total_piezas_detectadas', models.IntegerField(default=0, help_text='Número total de piezas segmentadas', verbose_name='Total piezas detectadas')),
                ('tiempo_promedio_captura_ms', models.FloatField(default=0.0, verbose_name='Tiempo promedio captura (ms)')),
                ('tiempo_promedio_segmentacion_ms', models.FloatField(default=0.0, verbose_name='Tiempo promedio segmentación (ms)')),
                ('tiempo_promedio_total_ms', models.FloatField(default=0.0, verbose_name='Tiempo promedio total (ms)')),
                ('confianza_promedio', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Confianza promedio')),
            ],
            options={
                'verbose_name': 'Estadísticas del Sistema',
                'verbose_name_plural': 'Estadísticas del Sistema',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SegmentacionDefecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(help_text='Clase del defecto segmentado', max_length=50, verbose_name='Clase')),
                ('confianza', models.FloatField(help_text='Confianza de la segmentación (0.0 - 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Confianza')),
                ('bbox_x1', models.IntegerField(verbose_name='BBox X1')),
                ('bbox_y1', models.IntegerField(verbose_name='BBox Y1')),
                ('bbox_x2', models.IntegerField(verbose_name='BBox X2')),
                ('bbox_y2', models.IntegerField(verbose_name='BBox Y2')),
                ('centroide_x', models.IntegerField(verbose_name='Centroide X')),
                ('centroide_y', models.IntegerField(verbose_name='Centroide Y')),
                ('area_mascara', models.IntegerField(help_text='Área en píxeles', verbose_name='Área de máscara')),
                ('coeficientes_mascara', models.JSONField(help_text='Coeficientes de la máscara de segmentación', verbose_name='Coeficientes de máscara')),
            ],
            options={
                'verbose_name': 'Segmentación de Defecto',
                'verbose_name_plural': 'Segmentaciones de Defectos',
                'ordering': ['-confianza'],
            },
        ),
        migrations.CreateModel(
            name='SegmentacionPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(help_text='Clase de la pieza segmentada', max_length=50, verbose_name='Clase')),
                ('confianza', models.FloatField(help_text='Confianza de la segmentación (0.0 - 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Confianza')),
                ('bbox_x1', models.IntegerField(verbose_name='BBox X1')),
                ('bbox_y1', models.IntegerField(verbose_name='BBox Y1')),
                ('bbox_x2', models.IntegerField(verbose_name='BBox X2')),
                ('bbox_y2', models.IntegerField(verbose_name='BBox Y2')),
                ('centroide_x', models.IntegerField(verbose_name='Centroide X')),
                ('centroide_y', models.IntegerField(verbose_name='Centroide Y')),
                ('area_mascara', models.IntegerField(help_text='Área en píxeles', verbose_name='Área de máscara')),
                ('ancho_mascara', models.IntegerField(verbose_name='Ancho de máscara')),
                ('alto_mascara', models.IntegerField(verbose_name='Alto de máscara')),
                ('coeficientes_mascara', models.JSONField(help_text='Coeficientes de la máscara de segmentación', verbose_name='Coeficientes de máscara')),
            ],
            options={
                'verbose_name': 'Segmentación de Pieza',
                'verbose_name_plural': 'Segmentaciones de Piezas',
                'ordering': ['-confianza'],
            },
        ),
    ]
