# Generated by Django 5.2.2 on 2025-09-30 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analisis_coples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analisiscople',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por'),
        ),
        migrations.AddField(
            model_name='analisiscople',
            name='configuracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis_realizados', to='analisis_coples.configuracionsistema', verbose_name='Configuración utilizada'),
        ),
        migrations.AddField(
            model_name='segmentaciondefecto',
            name='analisis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentaciones_defectos', to='analisis_coples.analisiscople', verbose_name='Análisis'),
        ),
        migrations.AddField(
            model_name='segmentacionpieza',
            name='analisis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentaciones_piezas', to='analisis_coples.analisiscople', verbose_name='Análisis'),
        ),
        migrations.AddIndex(
            model_name='analisiscople',
            index=models.Index(fields=['timestamp_procesamiento'], name='analisis_co_timesta_8de737_idx'),
        ),
        migrations.AddIndex(
            model_name='analisiscople',
            index=models.Index(fields=['estado'], name='analisis_co_estado_85481a_idx'),
        ),
        migrations.AddIndex(
            model_name='analisiscople',
            index=models.Index(fields=['tipo_analisis'], name='analisis_co_tipo_an_f0c1a7_idx'),
        ),
        migrations.AddIndex(
            model_name='analisiscople',
            index=models.Index(fields=['usuario'], name='analisis_co_usuario_1deb70_idx'),
        ),
    ]
