# Generated by Django 5.2.2 on 2025-10-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_coples', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisiscople',
            name='archivo_imagen',
            field=models.ImageField(blank=True, help_text='Imagen procesada con máscaras dibujadas', null=True, upload_to='analisis/', verbose_name='Archivo de imagen'),
        ),
    ]
